#!/bin/bash
set -euo pipefail

# shellcheck source=share/common.sh
. $LETSENCRYPT_SHAREDIR/common.sh

WHEN="tomorrow 02:05"

do_cron() {
    local domainname selfLink
    local tmpl='.items[] | .spec.host + ":" + .metadata.selfLink'
    get_routes | jq -er "$tmpl" \
        | while IFS=: read -r domainname selfLink; do
            log "Processing route $selfLink with domain $domainname."
            get_certificate "$domainname" "$selfLink"
        done
}

while true; do
    do_cron
    sleep $(( $(date -d "$WHEN" +%s) - $(date +%s) ))
done
