#!/bin/bash
set -euo pipefail

# shellcheck source=share/common.sh
. $LETSENCRYPT_SHAREDIR/common.sh

DOMAINNAME="$1"
SELFLINK="$2"
keyfile_="$(keyfile "$DOMAINNAME")"
certfile_="$(certfile "$DOMAINNAME")"
fullchainfile_="$(fullchainfile "$DOMAINNAME")"

pidfile=$LETSENCRYPT_DATADIR/get_certificate.pid

get_old_certificate() {
    if ! [ -f "$certfile_" ] || ! [ -f "$keyfile_" ] || ! [ -f "$fullchainfile_" ]
    then
        get_certs_from_route "$DOMAINNAME" "$SELFLINK"\
	    || echo "no old certificate found"
    fi
}

setup_api_key() {
    get_secret "$LETSENCRYPT_ACME_SECRET_NAME" \
         | mount_secret "$LETSENCRYPT_DATADIR"
}

get_new_certificate() {
    setup_api_key
    log "calling dehydrated with domain name '$DOMAINNAME'"
    dehydrated \
        --domain "$DOMAINNAME" \
        --challenge http-01 \
        --algo "$LETSENCRYPT_KEYTYPE" \
        --out "$LETSENCRYPT_DATADIR" \
        --privkey "$LETSENCRYPT_DATADIR/account-key" \
        --hook "$LETSENCRYPT_LIBEXECDIR/dehydrated-hook" \
        --config "$LETSENCRYPT_SHAREDIR/config" \
        --cron
}

# Try to get lock
exec 201>"$pidfile"
flock -x 201

get_old_certificate
if crt_valid_long_enough "$certfile_"; then
    log "Certificate for $DOMAINNAME still valid long enough."
else
    log "Getting new certificate for $DOMAINNAME"
    get_new_certificate "$DOMAINNAME"
    add_certificate_to_route "$DOMAINNAME" "$SELFLINK"
fi
