#!/bin/bash
set -euo pipefail

# shellcheck source=share/common.sh
. "$LETSENCRYPT_SHAREDIR/common.sh"

process_routes() {
    local domainname selfLink
    local tmpl='.object.spec.host + ":" + .object.metadata.selfLink'
    
    log "watching routes with selector $LETSENCRYPT_ROUTE_SELECTOR"
    
    watch_routes | jq -er --unbuffered "$tmpl" \
        | while IFS=: read -r domainname selfLink; do
            if [ -n domainname ] && [ -n selfLink ]; then
              log "Processing route $selfLink with domain $domainname."
              get_certificate "$domainname" "$selfLink"
            else
              log "$(watch_routes)"
            fi
            done
}

while true
do
    if ! process_routes; then
        err "Failure to watch routes; exiting."
        exit 1
    fi
done
