#!/bin/bash
set -euo pipefail

# shellcheck source=share/common.sh
. "$LETSENCRYPT_SHAREDIR/common.sh"

process_routes() {
    local domainname selflink
    local tmpl='.object.spec.host + ":" + .object.metadata.selfLink'
    log "watching routes with selector $LETSENCRYPT_ROUTE_SELECTOR"
    watch_routes | jq -er --unbuffered "$tmpl" \
        | while IFS=: read -r domainname selflink; do
            log "processing route $selflink with domain $domainname"
            get_certificate "$domainname"
            add_certificate_to_route "$domainname" "$selflink"
        done
}

while true
do
    if ! process_routes; then
        err "Failure to watch routes; exiting."
        exit 1
    fi
done
